---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: message
  image: busybox
  commands:
  - echo "README.md was changed"
  - touch file
  - mv file $file_{DRONE_COMMIT}
  - ls
