---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: semver
    image: cedrichopf/drone-semver
    settings:
      initial_version: 1.0.0
      autoincrement: true
      file: CHANGELOG.md

  - name: message
    image: busybox
    commands:
      - cat semver
