---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: message
    image: busybox
    environment:
      SECRET:
        from_secret: MY_SECRET
    commands:
      - echo "$SECRET"
      - ./parent.sh
