---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: message
    image: busybox
    # environment:
    #   DRONE_COMMIT_SHA_FIRST_SEVEN: c${DRONE_BRANCH//\//-}-c${DRONE_COMMIT_SHA:0:7}
    #   SOME_VAL: 0598408
    #   SOME_VAL1: 598408
    commands:
      - |
        ## TODO remove feature/aws-ma-poc later
        if [[ "$DRONE_BRANCH" =~ "^([a-zA-z]*-[0-9]*)" || "$DRONE_BRANCH" = "feature/aws-ma-poc" ]]; then 
          echo "Valid branch name $DRONE_BRANCH" 
        else 
          echo "Invalid branch name $DRONE_BRANCH. Please create your branch with the format '<JIRA Ticket>-<summary of change>', eg: SMT-1-create-entity" ; exit 1 
        fi
