---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: message
    image: busybox
    # environment:
    #   DRONE_COMMIT_SHA_FIRST_SEVEN: c${DRONE_BRANCH//\//-}-c${DRONE_COMMIT_SHA:0:7}
    #   SOME_VAL: 0598408
    #   SOME_VAL1: 598408
    commands:
      - |
        set -x
        if [[ "$DRONE_BRANCH" =~ "^([a-zA-z]*-[0-9]*)" ]]; then 
          echo "Valid branch name $DRONE_BRANCH" 
        else 
          echo "Invalid branch name $DRONE_BRANCH" ; exit 1 
        fi
