---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: message
    image: busybox
    environment:
      DRONE_COMMIT_SHA_FIRST_SEVEN: ${DRONE_COMMIT_SHA:0:7}
    commands:
      - echo "$DRONE_COMMIT_SHA_FIRST_SEVEN"
      - echo "$DRONE_COMMIT_SHA"
      - echo $${DRONE_COMMIT_SHA}
