---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: message
    image: busybox
    environment:
      MY_SECRET: "hello"
    commands:
      - echo "$MY_SECRET"
      - sh parent.sh
